[package]
name = "extreme"
version = "0.0.0"
authors = ["Tyler Neely <t@jujit.su>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
